# Copyright (c) 2023-2024 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: CI
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    # Run only on branches/commits and not tags
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    name: "Run linters"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          pip install -r requirements-dev.txt

      - name: Run Linters
        uses: pre-commit/action@v3.0.0

  install-job:
    name: "Install package"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install model generator package
        run: |
          pip install .

  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required packages
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          pip install -e .

      - name: unit test
        shell: bash
        run: |
          pytest \
            --junit-xml=./results/UnitTest/junit.xml \
            --cov-report=xml:results/CodeCoverage/cobertura-coverage.xml \
            --cov \
            --cov-branch

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: ./results/UnitTest/junit.xml
          summary: true
          update_check: true
          annotate_only: true

      - uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: results/CodeCoverage/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_complexity: true
          indicators: true
          output: both

      - run: |
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
